JackUtils: Custom JackGUI widgets
Custom JackGUI widgets
JackGUI extension :)
Functions
float jg_whell_float (jg_ctx_t *ctx, float value, float min, float max)
Float whell widget.
JG_API void jg_jackutils_topbar (jg_ctx_t *u, ju_ctx_t *j)
JackUtils Classic GUI topbar.
Detailed Description
JackGUI extension :)
Function Documentation
jg_jackutils_topbar()
JG_API void jg_jackutils_topbar (jg_ctx_t * u, ju_ctx_t * j)
JackUtils Classic GUI topbar.
Shows info about jhack, session manager, about window, etc.
Parameters
u JackGUI context
j JACKUTILS context
References jg_jackutils_icon(), jg_show_about(), ju_is_online(), ju_jack_info(), ju_length(), program_info::name, and program_info::version.